### ISSUE TITLE
Error in docs for 'scan' and 'scanRight'

### ISSUE THREAD

**Issue by phormio** [nullobject/fkit#18]
The JSDoc for `scan` has an example that uses `fold`, not `scan`:

https://github.com/nullobject/fkit/blob/edac82228c89bfa397ec09045708f844bf1a7e4c/src/list/fold.js#L120-L142

There is a similar error for `scanRight`:

https://github.com/nullobject/fkit/blob/edac82228c89bfa397ec09045708f844bf1a7e4c/src/list/fold.js#L144-L166

**Comment by nullobject** [comment]
Oops, thanks for letting me know. Will fix.
