### ISSUE TITLE
What are the benefits of this library compared to lodash fp?

### ISSUE THREAD

**Issue by dietergeerts** [nullobject/fkit#19]
I scanned this library quickly, but I could not see any benefit compared to using lodash-fp. So I wonder if there are some? https://github.com/lodash/lodash/wiki/FP-Guide

Maybe a section that explains why this library should be picked over others in certain situations would be nice, so it's clear.

**Comment by nullobject** [comment]
Hi @dietergeerts, you make a good point. I'm not doing a very good job differentiating FKit over any other choice (lodash, ramda, etc).

In my mind these are the benefits:

* Small focussed API.
* Sensible ordering of arguments to allow functions to be partially applied wherever possible.
* Good documentation (although Lodash FP is likely to sort out its documentation sooner or later).
* Most functions that operate on arrays also operate on strings.

**Comment by CrossEye** [comment]
My take (as a Ramda core member) is that FKit is close in spirit to Ramda.  They have different focuses but many overlapping functions and the same general spirit.  FKit is more concerned with Strings than is Ramda, and Ramda spends more time trying to inter-operate with other systems, especially with FantasyLand implementations.  But they feel very similar to work with.

Lodash/fp feels mostly like an afterthought to the main lodash library; and the documentation shows it.  (I agree, it likely will eventually catch up there.)  Lodash itself is a broader library with many more concerns.  Ramda is more focused on pure FP concerns like immutability and referential transparency.  FKit is the same with a smaller, more focused API.

**Comment by dietergeerts** [comment]
Thx for the info. As for Lodash-fp, there is good documentation, but yes, you have to look into two places for it. The official Lodash docs have the docs on how each thing works, while the fp docs have the conversion (args order etc....) documented.
